services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
      - ServiceUrls__ProductService=http://productservice:8080
      - ServiceUrls__CartService=http://cartservice:8080
      - ServiceUrls__UserService=http://userservice:8080
      - ServiceUrls__PaymentService=http://paymentservice:8080
      - ReverseProxy__Clusters__product-cluster__Destinations__product1__Address=http://productservice:8080/
      - ReverseProxy__Clusters__cart-cluster__Destinations__cart1__Address=http://cartservice:8080/
      - ReverseProxy__Clusters__user-cluster__Destinations__user1__Address=http://userservice:8080/
      - ReverseProxy__Clusters__payment-cluster__Destinations__payment1__Address=http://paymentservice:8080/
    ports:
      - "8080:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  cartservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
      - ServiceUrls__ProductService=http://productservice:8080
    ports:
      - "8082:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  paymentservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8083:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  productservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8084:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  userservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8085:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
